version: "3.8"

services:
  firestore:
    image: google/cloud-sdk
    command: >
      sh -c "gcloud emulators firestore start --host-port=0.0.0.0:8080"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "true"]
      retries: 3
      timeout: 30s
      interval: 5s